[package]
name = "egui_template"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emilernerfeldt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
egui = "0.6"

# Gives us persistence. Remove if you do like.
serde = { version = "1", features = ["derive"] }

# For compiling natively:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui_glium = "0.6"

# For compiling to web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
egui_web = "0.6"
js-sys = "0.3"
wasm-bindgen = "0.2"

# [patch.crates-io]
# egui = { git = "https://github.com/emilk/egui", rev = "db3fdbe6d3c1b2baf9cb71445f8dbbf8aded0e29" } # 2020-12-26
# egui_glium = { git = "https://github.com/emilk/egui", rev = "db3fdbe6d3c1b2baf9cb71445f8dbbf8aded0e29" } # 2020-12-26
# egui_web = { git = "https://github.com/emilk/egui", rev = "db3fdbe6d3c1b2baf9cb71445f8dbbf8aded0e29" } # 2020-12-26

[profile.release]
opt-level = 2 # fast and small wasm
